# edit this to include a job based on title keyword(s)
WHITELIST_JOB_TITLE_KEYWORDS = [
    "software engineer",
    "software developer",
    "web developer",
    "frontend",
    "front-end",
    "backend",
    "back-end",
    "back end",
    "full stack",
    "full-stack",
    "react",
    "vue",
    "node",
    "javascript",
    "typescript",
    "python developer",
    "django",
    "flask",
    "junior",
    "jr",
    "entry-level",
    "entry level",
    "mid",
    "web",
    "angular",
]

# edit this to exclude a job based on title keyword(s)
BLACKLIST_JOB_TITLE_KEYWORDS = [
    "data engineer",
    "azure",
    "gcp",
    "aws",
    "cloud engineer",
    "spark",
    "synapse",
    "mainframe",
    "etl",
    "observability",
    "performance",
    "devops",
    "site reliability",
    "sre",
    "platform engineer",
    "infrastructure",
    "ml",
    "ai",
    "security",
    "qa",
    "test",
    "support",
    "sysadmin",
    "embedded",
    "hardware",
    "desktop support",
    "help desk",
    "windows server",
    "lead",
    "senior",
    "sr",
    "staff",
    "principal",
]
