name: LinkedIn Job Scraper

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{secrets.SUPABASE_URL}}
      SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
      TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
      TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}

    steps:
      - uses: actions/checkout@v3

      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Playwright binaries
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-chromium-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            playwright-chromium-${{ runner.os }}-

      - name: 'Install Dependencies'
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run Scraper
        run: python app.py || exit 1
